### PR TITLE
Minor refactoring of cpp code

### PR DESCRIPTION
**Pull request by ChHaeni**
This PR is not necessary to merge at all, and I'm not mad at you if you don't merge it into dev!

I thought that one could optimize the C++ code a little bit by reducing the number of loops and vectors (it could even be further optimized by reducing the number of variables, but that would start biting code readability...). The gain in speed in the vignette examples is marginal, but maybe it could pay off for very large data sets? Even if not, I think that the code is slightly easier to read now... but maybe that's just me :-D

### CODE REVIEW

**Comment by ecoRoland2** [comment]
I would need to see some benchmarks showing that this actually does improve performance (or at least doesn't lead to worse performance) . I'm not enough of a C++ programmer to judge that because the compiler can optimize the code a lot and you need to understand compiler optimization to predict performance effects of code refactoring.

**Comment by sashahafner** [comment]
Cool!
I need to take a closer look after lunch, but I think I see that you combined the two `for (R_xlen_t i = 0; i < gl; ++i) {` loops into 1, and that let you keep `F` and `S` length 1 instead of indexing a longer vector with `F[i]` etc.
That makes sense, but I need to look more closely.

**Comment by ChHaeni** [comment]
> I would need to see some benchmarks showing that this actually does improve performance (or at least doesn't lead to worse performance) . I'm not enough of a C++ programmer to judge that because the compiler can optimize the code a lot and you need to understand compiler optimization to predict performance effects of code refactoring.

@sashahafner do you have some good example data sets to run benchmarks against?

**Comment by sashahafner** [comment]
> > I would need to see some benchmarks showing that this actually does improve performance (or at least doesn't lead to worse performance) . I'm not enough of a C++ programmer to judge that because the compiler can optimize the code a lot and you need to understand compiler optimization to predict performance effects of code refactoring.
> 
> @sashahafner do you have some good example data sets to run benchmarks against?

Yes, I have this all set up here: https://github.com/AU-BCE-EE/Hafner-2023-ALFAM2-dev/blob/main/speed/scripts/speed_comp_ubuntu.R

The script could be simpler I am sure.
But it is a bit tricky because the different options require different input data and different actual arguments.
But you should be able to copy it and modify as needed to compare two versions of the package.

**Comment by ChHaeni** [comment]
> > > I would need to see some benchmarks showing that this actually does improve performance (or at least doesn't lead to worse performance) . I'm not enough of a C++ programmer to judge that because the compiler can optimize the code a lot and you need to understand compiler optimization to predict performance effects of code refactoring.
> > 
> > 
> > @sashahafner do you have some good example data sets to run benchmarks against?
> 
> Yes, I have this all set up here: https://github.com/AU-BCE-EE/Hafner-2023-ALFAM2-dev/blob/main/speed/scripts/speed_comp_ubuntu.R
> 
> The script could be simpler I am sure. But it is a bit tricky because the different options require different input data and different actual arguments. But you should be able to copy it and modify as needed to compare two versions of the package.

Great! I'll have a look into it possibly tonight or tomorrow :+1:

**Comment by ChHaeni** [comment]
I've tested on my debian system (gcc 10) and my windows VM (gcc 13) and performance seems to be (disappointingly) equal with a marginal increase in speed with the new version.

I'd still merge this PR since I find the new code easier to follow.

I'm gonna force push an additional commit where I found a unused, declared r5 double...

**Comment by ChHaeni** [comment]
ah, and should I commit the testing script to this repo? I think it's not necessary since I don't expect much more performance related changes in alfam2 (unless we'd want to re-implement parallelism...)

**Comment by ChHaeni** [comment]
I just adapted your script and didn't really change much. Gonna paste it here for the record:

```r
# Compare speed of alfam2() versions

# Packages
library(data.table)

# fix working directory for chhaeni ;-)
working_dir <- switch(Sys.info()['user']
    , christoph = 
    , hac5 = '~/repos/5_GitHub/Hafner-2023-ALFAM2-dev/speed/scripts'
    , stop('add path to working directory @ line 10!')
)
# fix windows path
if (Sys.info()['sysname'] == 'Windows') working_dir <- sub('\\~', 'E:', working_dir)

setwd(working_dir)

# Functions
source('../../functions/rounddf.R')

# Locations for reference vs. case version
# use hidden objects so rm(list = ls()) won't catch them ;-)
# names provide git reference (branch, commit, tag, ...)
.rver <- c('au-bce-ee/alfam2@dev' = './ref-version')
.cver <- c('chhaeni/alfam2@c95df75' = './case-version')

# clean up on exiting R (if not done before)
reg.finalizer(.GlobalEnv, \(env) evalq({if (dir.exists(.rver)) unlink(.rver, recursive = TRUE)}, env), onexit = TRUE)
reg.finalizer(.GlobalEnv, \(env) evalq({if (dir.exists(.cver)) unlink(.cver, recursive = TRUE)}, env), onexit = TRUE)

setwd(working_dir)

# Functions
source('../../functions/rounddf.R')

# create dirs
dir.create(.rver)
dir.create(.cver)

# install versions
td1 <- tempfile()
td2 <- tempfile()
dir.create(td1)
dir.create(td2)
remotes::install_github(names(.rver), lib = .rver, destdir = td1, force = TRUE)
remotes::install_github(names(.cver), lib = .cver, destdir = td2, force = TRUE)

# Need new version of package first for incorp data processing
library(ALFAM2, lib.loc = .cver)

# Input data
# Many plots 
set.seed(123)
d <- data.frame(ct = 1:168, app.mthd = 'bc', 
                man.dm = 7, man.ph = 7, man.source = 'cattle', 
                air.temp = rnorm(168, mean = 10, sd = 5), 
                wind.2m = rnorm(168, mean = 5, sd = 1),
                tan.app = 100)

# Without incorporation.
nplots <- 1000
datp <- d[rep(1:nrow(d), nplots), ]
datp$id <- rep(1:nplots, each = nrow(d))

# Add incorporation.
datpi <- datp
datpi$t.incorp <- 3
datpi$incorp <- 'shallow'

# Incorp needs prep if used with flatout = TRUE
datpip <- alfam2(datpi, pars = ALFAM2::alfam2pars02, time.incorp = 't.incorp', 
                 app.name = 'tan.app', group = 'id', prep.dum = TRUE, warn = TRUE, 
                 value = 'incorp')

# Many times
set.seed(123)
ntimes <- 1E6
d <- data.frame(ct = sort(c(1:(ntimes - 1) * 168 / (ntimes - 1), 3)), app.mthd = 'bc', 
                man.dm = 7, man.ph = 7, man.source = 'cattle', 
                air.temp = rnorm(ntimes, mean = 10, sd = 5), 
                wind.2m = rnorm(ntimes, mean = 5, sd = 1),
                tan.app = 100)

# Without incorporation.
datt <- d

# Add incorporation.
datti <- datt
datti$t.incorp <- 3
datti$incorp <- 'shallow'

# Incorp needs prep if used with flatout = TRUE
dattip <- alfam2(datti, pars = ALFAM2::alfam2pars02, time.incorp = 't.incorp', 
                 app.name = 'tan.app',  prep.dum = TRUE, warn = TRUE, 
                 value = 'incorp')

# Results matrix
stdev <- times <- matrix(NA, nrow = 4, ncol = 2, 
                         dimnames = list(c('plots', 'plots-incorp', 'times', 'times-incorp'), 
                                         c('ref', 'case')))

# Run old version first
for (j in 1) {

  if ('ALFAM2' %in% (.packages())) {
      detach('package:ALFAM2', unload = TRUE)
      try(library.dynam.unload('ALFAM2', .rver), silent = TRUE)
      try(library.dynam.unload('ALFAM2', .cver), silent = TRUE)
  }
  library(ALFAM2, lib.loc = .rver)

  # Many plots, no incorporation
  nits <- 7
  tt <- numeric(nits)
  for (i in 1:nits) {
    tt[i] <- system.time(outp.o <- alfam2(datp, pars = ALFAM2::alfam2pars02, app.name = 'tan.app', 
                                group = 'id', prep.dum = TRUE, prep.incorp = TRUE, warn = FALSE, check = TRUE))[3]
  }
  
  times['plots', j] <- mean(tt)
  stdev['plots', j] <- sd(tt)
  
  # Many plots, with incorporation.
  nits <- 7
  tt <- numeric(nits)
  for (i in 1:nits) {
    args(alfam2)
    tt[i] <- system.time(outpi.o <- alfam2(datpi, pars = ALFAM2::alfam2pars02, time.incorp = 't.incorp', 
                                app.name = 'tan.app', group = 'id', prep.dum = TRUE, prep.incorp = TRUE, warn = FALSE, check = TRUE))[3]
  }
  
  times['plots-incorp', j] <- mean(tt)
  stdev['plots-incorp', j] <- sd(tt)
  
  # Many times, no incorporation
  nits <- 7
  tt <- numeric(nits)
  for (i in 1:nits) {
    tt[i] <- system.time(outt.o <- alfam2(datt, pars = ALFAM2::alfam2pars02, app.name = 'tan.app', 
                                prep.dum = TRUE, prep.incorp = TRUE, warn = FALSE, check = TRUE))[3]
  }
  
  times['times', j] <- mean(tt)
  stdev['times', j] <- sd(tt)
  
  # Many times, with incorporation
  
  nits <- 7
  tt <- numeric(nits)
  for (i in 1:nits) {
    tt[i] <- system.time(outti.o <- alfam2(datti, pars = ALFAM2::alfam2pars02, time.incorp = 't.incorp', 
                                app.name = 'tan.app', prep.dum = TRUE, prep.incorp = TRUE, warn = FALSE, check = TRUE))[3]
  }
  
  times['times-incorp', j] <- mean(tt)
  stdev['times-incorp', j] <- sd(tt)
}


# Run new version with and without flatout option
if ('ALFAM2' %in% (.packages())) {
  detach('package:ALFAM2', unload = TRUE)
  try(library.dynam.unload('ALFAM2', .rver), silent = TRUE)
  try(library.dynam.unload('ALFAM2', .cver), silent = TRUE)
}
library(ALFAM2, lib.loc = .cver)

for (j in 2) {

  dp <- datp
  dt <- datt

  if (j == 3) {
    prep.incorp <- FALSE
    check <- FALSE
    dpi <- datpip
    dti <- dattip
  } else {
    prep.incorp <- TRUE
    check <- TRUE
    dpi <- datpi
    dti <- datti
  }
  
  # Many plots, no incorporation
  nits <- 7
  tt <- numeric(nits)
  for (i in 1:nits) {
    tt[i] <- system.time(outp.n <- alfam2(dp, pars = ALFAM2::alfam2pars02, app.name = 'tan.app', 
                                group = 'id', prep.dum = TRUE, warn = TRUE, prep.incorp = TRUE, check = check))[3]
  }
  
  times['plots', j] <- mean(tt)
  stdev['plots', j] <- sd(tt)
  
  # Many plots, with incorporation.
  nits <- 7
  tt <- numeric(nits)
  for (i in 1:nits) {
    tt[i] <- system.time(outpi.n <- alfam2(dpi, pars = ALFAM2::alfam2pars02, time.incorp = 't.incorp', 
                                app.name = 'tan.app', group = 'id', prep.dum = TRUE, warn = TRUE, prep.incorp = prep.incorp, check = check))[3]
  }
  
  times['plots-incorp', j] <- mean(tt)
  stdev['plots-incorp', j] <- sd(tt)
  
  # Many times, no incorporation
  nits <- 7
  tt <- numeric(nits)
  for (i in 1:nits) {
    tt[i] <- system.time(outt.n <- alfam2(dt, pars = ALFAM2::alfam2pars02, app.name = 'tan.app', 
                                prep.dum = TRUE, warn = FALSE, prep.incorp = TRUE, check = check))[3]
  }
  
  times['times', j] <- mean(tt)
  stdev['times', j] <- sd(tt)
  
  # Many times, with incorporation
  
  nits <- 7
  tt <- numeric(nits)
  for (i in 1:nits) {
    tt[i] <- system.time(outti.n <- alfam2(dti, pars = ALFAM2::alfam2pars02, time.incorp = 't.incorp', 
                                app.name = 'tan.app', prep.dum = TRUE, warn = FALSE, prep.incorp = prep.incorp, check = check))[3]
  }
  
  times['times-incorp', j] <- mean(tt)
  stdev['times-incorp', j] <- sd(tt)
}

# Sort out results
cv <- 100 * stdev / times
times <- rounddf(times, 3, func = signif)
cv <- rounddf(cv, 3, func = signif)

# Make sure incorporation and other results with fast options are correct
# Note that *.n results are fast because they were last run in loop
if (!all(c1 <- isTRUE(all.equal(outp.o$er, outp.n$er)), 
         c2 <- isTRUE(all.equal(outpi.o$er, outpi.n$er)), 
         c3 <- isTRUE(all.equal(outt.o$er, outt.n$er)), 
         c4 <- isTRUE(all.equal(outti.o$er, outti.n$er)))) {
  print(c(c1, c2, c3, c4))
  stop('Output problem--results are not identical with and without incorporation pre-processing!')
}

apply(times, 2, summary)
apply(cv, 2, summary)

# # Export results
# write.csv(times, '../output/times_ubuntu_hashes.csv')
# write.csv(cv, '../output/cv_ubuntu_hashes.csv')

```

**Pull request merged**
